= Globals
:sourcedir: ../

When programming in Javascript there is always a global scope.
Depending on which Javascript engine/environment you are in, the global scope is different.

TIP: Useful reading: https://developer.mozilla.org/en-US/docs/Glossary/Global_object[Global object, window=_blank, opts=nofollow]

== Browser

In the browser, the global scope is the `window` object. The `window` object contains the `document` object that represents the current web page. The `document` object contains functions and properties that allow you to inspect and manipulate the web page.

== Enonic XP Framework

In the Enonic XP Framework the global scope contains a bunch of objects and functions that are useful when developing applications.

TIP: You can read about them https://developer.enonic.com/docs/xp/stable/framework/globals[here,window=_blank,opts=nofollow].

== Source code

.src/main/resources/lib/tutorial-jest/getAppConfig.ts
[source, typescript]
----
include::{sourcedir}src/main/resources/lib/tutorial-jest/getAppConfig.ts[]
----

== Test without mock

Let's try to write a simple test for the function above:

[source, typescript]
----
import {
    describe,
    expect,
    test as it
} from '@jest/globals';
import { getAppConfig } from './getAppConfig';


describe('getAppConfig', () => {
    it('should return the application config', () => {
        expect(getAppConfig()).toEqual({});
    });
});
----

If you try to run this test without mocking some props on the global object, it will fail with the following error message:

[source, shell]
----
ReferenceError: log is not defined
----

== Test with mock

To fix that, both the `log` and `app` objects must be mocked.

This can be achieved in multiple ways. When it comes to static values like the global `app` object, the following can be added to the `serverSideConfig` in the `jest.config.ts` file:

.jest.config.ts
[source, typescript]
----
globals: {
    app: {
        name: 'com.example.tutorial.jest',
        config: {
            default: true,
        },
        version: '1.0.0'
    },
},
----

But when it comes to functions like `log.info`, a setup file can be used. It will run before the execution of each test file:

.src/jest/server/setupFile.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/setupFile.ts[]
----

Then add the following to the `serverSideConfig` in `jest.config.ts` file:

.jest.config.ts
[source, typescript]
----
setupFiles: ['<rootDir>/src/jest/server/setupFile.ts'],
----

The above will mock default values for the global `app` and `log` objects. The values can be augmented in the test files.

To avoid type errors when accessing those objects, you can make a type declaration file referencing `@enonic-types/global`

.src/jest/server/global.d.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/global.d.ts[]
----

Then you can import and use those types in the test file:

.src/jest/server/getAppConfig.test.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/getAppConfig.test.ts[]
----

== Summary

In this tutorial, you learned how to mock global objects in the Enonic XP Framework when writing tests with Jest.

Let's move on to the next tutorial to learn how to link:mock[mock] functions and write our first "real" test for a Enonic XP Framework server-side source code file.
