= Mocking Globals
:sourcedir: ../

This chapter introduces the concept of mocking.

== Introduction

Mocking is the concept of creating fake objects that stand in for real objects in the system. This way, you may test or simulate bigger parts of a system - even without that system being actually available.

== Globals

When programming in Javascript there is always a global scope. Depending on which Javascript engine/environment you are in, the global scope is different.

TIP: Useful reading: https://developer.mozilla.org/en-US/docs/Glossary/Global_object[Global object^]

== Browser

In the browser, the global scope is the `window` object. The `window` object contains the `document` object that represents the current web page. The `document` object contains functions and properties that allow you to inspect and manipulate the web page.

== XP Framework

In the Enonic XP Framework the global scope contains a bunch of objects and functions that are useful when developing applications.

TIP: You can read about them https://developer.enonic.com/docs/xp/stable/framework/globals[here^].

== Source code

Let's start by adding some more code we can test:

.src/main/resources/lib/tutorial-jest/getAppConfig.ts
[source, typescript]
----
include::{sourcedir}src/main/resources/lib/tutorial-jest/getAppConfig.ts[]
----

== Test without mock

Then, we write a simple test for the function above:

[source, typescript]
----
import {
    describe,
    expect,
    test as it
} from '@jest/globals';
import { getAppConfig } from './getAppConfig';


describe('getAppConfig', () => {
    it('should return the application config', () => {
        expect(getAppConfig()).toEqual({});
    });
});
----

If you try to run this test without mocking some props on the global object, it will fail with the following error message:

[source, shell]
----
ReferenceError: log is not defined
----

== Test with mock

To fix that, both the `log` and `app` objects must be mocked.

This can be achieved in multiple ways. When it comes to static values like the global `app` object, the following can be added to the `serverSideConfig` within your `jest.config.ts` file:

.jest.config.ts - serverSideConfig
[source, typescript]
----
globals: {
    app: {
        name: 'com.example.tutorial.jest',
        config: {
            default: true,
        },
        version: '1.0.0'
    },
},
----

A more flexible solution, that also let you mock functions, like `log.info` is to use a setup file.
It will run before the execution of each test file.

Create a setup file:

.src/jest/server/setupFile.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/setupFile.ts[]
----

Then, register it in your `serverSideConfig`:

.jest.config.ts - serverSideConfig
[source, typescript]
----
setupFiles: ['<rootDir>/src/jest/server/setupFile.ts'],
----

This will mock default values for the global `app` and `log` objects, and the values can be augmented in the test files.


== Types

To avoid type errors when accessing those objects, you can add a type declaration file referencing `@enonic-types/global`.

.src/jest/server/global.d.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/global.d.ts[]
----

Then, import and use those types in your test file:

.src/jest/server/getAppConfig.test.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/getAppConfig.test.ts[]
----

== Summary

In this chapter you learned how to mock global objects in the Enonic XP Framework when writing tests with Jest.

Let's move on to the next chapter and learn how to <<mock#,mock functions>> and write our first "real" test for Enonic server-side code.
