= Testing with Jest and Mock XP
:toc: right
:experimental:
:sourcedir: ../

This tutorial introduces you to the Jest testing framework, and how to integrate it in an Enonic application.

== Introduction

Jest is a highly adopted testing framework that supports TypeScript, mocking, and a lot,
lot more.

A special feature of this setup is that tests can be executed standalone, independently of Enonic XP. Thus, the tests will finish faster and be more flexible to execute.

TIP: For more details, visit the https://jestjs.io/[Jest documentation^].

This guide will show you how to:

1. Create a <<project#,Project>> with Jest environment already set up.
2. Write a simple <<test#,test>> without any mocks
3. Write a test for server-side code manually <<mock#,mocking>> Java libraries
4. Write a test for server-side code using <<mock-xp#, Mock XP>>
5. Write a test for <<client-side#, client-side>> code

== Advanced topics

In addition to the main topics, you might want to learn about these advanced topics:

* Set up <<coverage#,Coverage>> with Github Actions
* <<colocation#,Colocate>> tests with the code they test

== Additional reading

If you want to learn how to add Jest to an existing project, read the https://developer.enonic.com/docs/typescript-starter/stable/test[Testing] chapter of the https://developer.enonic.com/docs/typescript-starter/stable[TypeScript Starter] documentation.
