= Mock XP
:sourcedir: ../

When it comes to mocking more complex things (such as interaction with Content and Node APIs) Enonic has a library called `@enonic/mock-xp` that can help you with that.

== Install Mock XP

[source, shell]
----
npm install --save-dev @enonic/mock-xp
----

== Source code

Let's write a test for the following controller:

.src/main/resources/controllers/preview.ts
[source, typescript]
----
include::{sourcedir}src/main/resources/controllers/preview.ts[]
----

== The test

In this test `mock-xp` is used to set up a project repo, a person folder, a couple of images, and a couple content items (of type `person`) which reference the images.

In addition, mock-xp's `Log` is used to get nice colorful logging.

In order for `libPortal.getContent()` to work, `request` property is set on the `libPortal` object.

Finally, the `/lib/thymeleaf` 's `render` mock simply returns the model object, so the actual html rendering is not triggered.

NOTE: If anyone is able to find or create a test for thymeleaf rendering, please let us know :)

.src/main/resources/controllers/preview.test.ts
[source, typescript]
----
include::{sourcedir}src/main/resources/controllers/preview.test.ts[]
----
