= Mocking functions
:sourcedir: ../

This chapter covers mocking functions and Enonic libraries.

== Source code

To demonstrate the power of mocking, let's make a simple Typescript using a standard Enonic library:

.src/main/resources/lib/tutorial-jest/sanitize.ts
[source, TypeScript]
----
include::{sourcedir}src/main/resources/lib/tutorial-jest/sanitize.ts[]
----

== Test without mock

Trying to run this simple test ...

[source, TypeScript]
----
import {
    describe,
    expect,
    test as it
} from '@jest/globals';
import { sanitize } from '/lib/tutorial-jest/sanitize';


describe('sanitize', () => {
    it('should return the first 10 numbers in the fibonacci sequence', () => {
        expect(sanitize("Piña CØLADÆ <script>alert('hi!');</script>"))
            .toEqual('pina-coladae-script-alerthi-script');
    });
});
----

... will fail with the following error message:

[source, Terminal]
----
Cannot find module '/lib/xp/common' from 'src/main/resources/lib/tutorial-jest/sanitize.ts'
----

This happens because the module file `/lib/xp/common` isn't available in the test environment. It only exists inside the compiled Enonic application file, which is used at runtime in the Enonic XP server.

In order to run the test successfully, a "fake" version of the module must be made available in the test environment. This is where mocking comes in handy.

== Adding the mock

Add the following test to your project:

.src/jest/server/sanitize.test.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/sanitize.test.ts[]
----

Here, `sanitize` is no longer "statically" imported at the beginning of the file. This is because the mock must be set up before the import is done. That's why a dynamic import in each test is used instead.

Obviously this mock doesn't cover ascii-folding for the whole unicode range, but is sufficient enough to run this test.

== Summary

This guide showed how to mock an Enonic library invoked by a Typescript. This is neccessary when you want to test your code in a controlled environment, without having to rely on the actual library being present.

Writing mocks for entire libraries can be a bit tedious, so in the next chapter we will rather use the <<mock-xp#,Mock XP>> library.
