= Mock XP
:sourcedir: ../

In this chapter we introduce the Mock XP library.

== Introduction

When it comes to mocking more complex things (such as interaction with Content and Node APIs) Enonic has a library called `@enonic/mock-xp` that can help you with some of the heavy lifting.

== Install Mock XP

[source, shell]
----
npm install --save-dev @enonic/mock-xp
----

== Source code

Let's add a test for the following controller:

.src/main/resources/controllers/preview.ts
[source, typescript]
----
include::{sourcedir}src/main/resources/controllers/preview.ts[]
----

== Tests

In order for the test file to not become overly large, it's been split it into smaller parts:

=== Mock Portal Library

TODO: What does this do?

.src/jest/server/mockXP.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/mockXP.ts[]
----

=== The test

In this test `mock-xp` is used to set up a project repo, a person folder, a couple of images, and a couple content items (of type `person`) which reference the images.

In addition, mock-xp's `Log` is used to get nice colorful logging.

In order for `libPortal.getContent()` to work, `request` property is set on the `libPortal` object.

.src/jest/server/preview.test.ts
[source, typescript]
----
include::{sourcedir}src/jest/server/preview.test.ts[]
----

== Summary

This guide, showed how to write tests for Enonic XP applications using Jest in combination with Mock XP.

Mock XP was used to mock the Enonic XP *portal* API.

The next tutorial will show how to write a link:client-side[client-side] test for an Enonic XP application.
