= Setup
:sourcedir: ../

This chapter covers setting up Jest for your Enonic app.

== Sample project

You may follow the steps in this guide to configure Jest for an existing project. For simplicity, we will base this tutorial on the Enonic intro app.

To create a project for the tutorial, run the following command:

  enonic project create -r starter-ts -d jest-tutorial

This will create an app and place it in a folder called `jest-tutorial`.


== Node modules

In order to write tests in TypeScript and run them using Jest, a few Node modules need to be installed.

Run the following command at the root of the Enonic project you created in the previous step:

[source, Terminal]
----
npm install --save-dev jest-environment-jsdom ts-node ts-jest
----

== Configuration

Next, you will need to add and tune a few configuration files:

=== jest.config.ts

Jest needs to be configured to run Typescript tests. This is done by creating a `jest.config.ts` file in the root of the project:

.jest.config.ts
[source, Typescript]
----
include::{sourcedir}jest.config.ts[]
----

Read more about configuring Jest https://jestjs.io/docs/configuration[here^].

=== tsconfig.json

In an Enonic Typescript project there can be both server-side and client-side code. In order for such code to be properly type checked and compiled, multiple `tsconfig.json` files are used.

When running tests the Typescript configuration files might need to look slightly different. This is the case for the `src/jest/client/tsconfig.json` and `src/jest/server/tsconfig.json` files:

.src/jest/client/tsconfig.json
[source, json]
----
include::{sourcedir}src/jest/client/tsconfig.json[]
----

.src/jest/server/tsconfig.json
[source, json]
----
include::{sourcedir}src/jest/server/tsconfig.json[]
----

== Execution

Finally, we wire the test command to execute Jest tests.

=== Using NPM

In order to run tests the following needs to be added to the `package.json` file:

.package.json
[source, json]
----
{
  "scripts": {
    "test": "jest --no-cache --coverage"
  }
}
----

You should now be able to run the tests with the following command:

[source, shell]
----
npm test
----

NOTE: You may also run a specific test like this: `npm test src/jest/server/fibonacci.test.ts`


=== Using Enonic CLI

You may also run the tests using Enonic CLI. CLI uses the default build system (Gradle), so you must update the `build.gradle` file with the following lines:

.build.gradle
[source, gradle]
----
tasks.register('npmTest', NpmTask) {
    args = [
        'run',
        'test'
    ]
    dependsOn npmInstall
    environment = [
        'FORCE_COLOR': 'true',
    ]
    inputs.dir 'src/jest'
    outputs.dir 'coverage'
}

test.dependsOn npmTest
----

As you can see, this simply tells Gradle to invoke the NPM's test script.
You may now test with the following command as well:

[source, shell]
----
enonic project test
----


== Summary

With the above setup in place, it is possible to write tests in Typescript and run them using Jest.
The tests will be run on every build and the coverage will be reported.

Let's learn how to write our first <<test#,test>>.
