= Setup
:sourcedir: ../

Setting up Jest in your Enonic project

== Node modules

In order to write tests in Typescript and run them using Jest, a bunch of node modules needs to be installed.

Run the following command at the root of your project:

[source, shell]
----
npm install --save-dev jest-environment-jsdom ts-node ts-jest
----

== Configuration

Next, you will need to add and tune a set of configuration files:


=== jest.config.ts

Jest needs to be configured to run Typescript tests. This is done by creating a `jest.config.ts` file in the root of the project:

.jest.config.ts
[source, Typescript]
----
include::{sourcedir}jest.config.ts[]
----

Read more about configuring Jest here: https://jestjs.io/docs/configuration

=== tsconfig.json

In an Enonic Typescript project there can be both server-side and client-side code. In order for such code to be properly type checked and compiled, multiple `tsconfig.json` files are used.

When running tests the Typescript configuration files might need to look slightly different. This is the case for the `src/jest/client/tsconfig.json` and `src/jest/server/tsconfig.json` files:

.src/jest/client/tsconfig.json
[source, json]
----
include::{sourcedir}src/jest/client/tsconfig.json[]
----

.src/jest/server/tsconfig.json
[source, json]
----
include::{sourcedir}src/jest/server/tsconfig.json[]
----

== Execution

Finally, we wire the test commands to execute Jest

=== package.json

In order to run tests the following needs to be added to the `package.json` file:

.package.json
[source, json]
----
{
  "scripts": {
    "test": "jest --no-cache --coverage"
  }
}
----

You should now be able to run the tests with the following command:

[source, shell]
----
npm test
----

NOTE: You may also run a specific test like this: `npm test src/jest/server/fibonacci.test.ts`


=== build.gradle

Enonic uses Gradle as the main build system, to support running test from Enonic CLI, update your `build.gradle` file with these lines:

.build.gradle
[source, gradle]
----
tasks.register('npmTest', NpmTask) {
    args = [
        'run',
        'test'
    ]
    dependsOn npmInstall
    environment = [
        'FORCE_COLOR': 'true',
    ]
    inputs.dir 'test'
    outputs.dir 'coverage'
}

test.dependsOn npmTest
----

You may now tests with the following command as well:

[source, shell]
----
enonic project test
----


== Summary

With the above setup in place, it is possible to write tests in Typescript and run them using Jest.
The tests will be run on every build and the coverage will be reported.

Let's learn how to write our first link:test[test].
